name: 'Terraform'

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/account.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Write GCP credentials to file
        run: echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/account.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false

      # New step: Set up Python version 3.13.5
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.5'  # Use your local Python version here

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      # Run the main.py script from the root
      - name: Run Python script
        run: python main.py  # Since the script is in the root of the repo
